//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayar
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Employee
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual T_Country T_Country { get; set; }
        public virtual T_Department T_Department { get; set; }
    }
}
